---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age10wq70nfm0vhcx9wax24atnv6wwmugypa0vd8gdgkp3spwnr4pdlqykskkh
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age10wq70nfm0vhcx9wax24atnv6wwmugypa0vd8gdgkp3spwnr4pdlqykskkh
