# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:K2QP9IpX5MkjTGg=,iv:G+gFlr6eZgGjoOkGiDTyHXOf5WlIeNwOWvSZyJV5tlI=,tag:hmGdbcLssVsvHnde+4ma1w==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:J1joalww2gOuMnsflSb6FNOnc5pN2Q==,iv:J+5ptjiVRurvIdjiYwnsqnpx74hqYngIELj6Stp+ACk=,tag:9M3UrxK0tMg7ohs20rf6fQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10wq70nfm0vhcx9wax24atnv6wwmugypa0vd8gdgkp3spwnr4pdlqykskkh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUi9QSkxWQlhZNHpXcm4z
            MnpuWlJ1T09WVUoveFB5QmdrQncxSGh6UEdjCnRjN0t0dmpEamhvZTU1ZVJJWHBZ
            Q1VqcXZuTGJDY1NoMzBGdUM3VkE3WmMKLS0tIDZGK2JXcldrcEp6YmlicG1qaTEz
            VmNtMkM5cy9TVlJVYm9jc0srR2J3MWcKlIER/8fPI4D87HI0owjuY4EJe693Q5Ja
            pghB9Fw/1DP5NWEzh33UuTQp8turK0bH9OC+MW6Ab/6sEBH84i5/kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-15T01:20:08Z"
    mac: ENC[AES256_GCM,data:BQGEvvvN0LtGVhQ3GNslMrQbl6Z+J/vqM7ks3VzmUCDGszYWTvu6OxiEmXKDvgL4e/bLhCVCARo8QL6KUDD+eUJVVxrE7mkDsH4TJ45/eIfjrzIQJNdZfVeKat86bKv4fwo5vlC98t+q5j9xcRfPRqUqZ19EhRcF8cOwdyJH8P0=,iv:WvH85JvefeZtjNzZmGaxZF+jIin5Rt/EDA57pEJvI3o=,tag:XDPAKb/a6hKopP4ZUgIcfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
