---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/New_York
  METALLB_LB_RANGE: 10.10.11.100-10.10.11.230
  METALLB_K8S_GATEWAY_ADDR: 10.10.11.220
  METALLB_INGRESS_ADDR: 10.10.11.221
